# Generated by Django 4.2.4 on 2023-08-15 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('High Priority', 'High Priority'), ('Low Priority', 'Low Priority'), ('Mid Priority', 'Mid Priority')], max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
