# Generated by Django 4.2.4 on 2023-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Mid Priority', 'Mid Priority'), ('Low Priority', 'Low Priority')], max_length=30),
        ),
    ]
