# Generated by Django 4.2.4 on 2023-08-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_end',
        ),
    ]
